### ISSUE TITLE
500 Internal Server error on fresh install

### ISSUE THREAD

**Issue by hoover900** [RikudouSage/LemmySchedule#44]
I'm again getting the 500 internal server error and can't figure it out.
Deleting all of files generated by the docker container as well as removing the docker volume does nothing. Thought it might be the cookies and or cache on my browser so I spun up a new profile, same thing. Tried a different browser and still got the same issue.

The one thing that did work was changing what Lemmy account I signed in with. I primary use Lemmy-Schelude with my lemmynsfw account, but using my sh.itjust.works account works just fine. Pretty sure that both instances are running the latest stable version of Lemmy.

This is the error I when trying to schedule a post
```
[Fri Feb 28 01:52:06.905323 2025] [php:notice] [pid 42:tid 42] [client 192.168.1.21:43254] [critical] Uncaught PHP Exception Twig\\Error\\RuntimeError: "An exception has been thrown during the rendering of a template ("Too few arguments to function Rikudou\\LemmyApi\\Response\\View\\InstanceBlockView::__construct(), 2 passed in /var/www/html/vendor/rikudou/lemmy-api/src/Response/AbstractResponseDto.php on line 116 and exactly 3 expected")." at create.html.twig line 61, referer: http://unas.hanlan:8074/post/list

192.168.1.21 - - [28/Feb/2025:01:52:06 +0000] "GET /post/create HTTP/1.1" 500 1341 "http://unas.hanlan:8074/post/list" "Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0"
```
Let me know if you need anymore information

Any insight would be greatly appreciated

**Comment by hoover900** [comment]
okay, this is because LemmyNSFW is still on Lemmy 1.9.3

**Comment by RikudouSage** [comment]
Fixed it anyway, it should work on 0.19.3. Will do a release as soon as the build passes.
